version: "3"
networks:
  development:
  test:
volumes:
  db_data:
  gem_cache:
  shared_data:
services:
  pom_tracker_db:
    image: postgres:13.4-alpine
    container_name: pom_tracker_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
      - test
    environment:
      POSTGRES_USER: 'pom_tracker'
      POSTGRES_PASSWORD: 'pom tracker dev'
    ports:
      - 5430:5432

  pom_tracker_app:
    build: .
    container_name: pom_tracker_app
    volumes:
      - .:/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 3001:3000
    stdin_open: true
    tty: true
    environment:
      POM_TRACKER_DATABASE_PASSWORD: 'pom tracker dev'
      POM_TRACKER_DB_HOST: pom_tracker_db
      RAILS_ENV: 'development'
    entrypoint: 'dev-entrypoint.sh'
    command: ['rails', 'server', '-p', '3000', '-b', '0.0.0.0']
    depends_on: 
      - pom_tracker_db

  pom_tracker_test:
    image: pom-tracker-rails_pom_tracker_app
    container_name: pom_tracker_test
    volumes:
      - .:/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - test
    ports:
      - 3002:3000
    stdin_open: true
    tty: true
    environment:
      POM_TRACKER_DATABASE_PASSWORD: 'pom tracker dev'
      POM_TRACKER_DB_HOST: pom_tracker_db
      RAILS_ENV: 'test'
    entrypoint: 'test-entrypoint.sh'
    command: ["rails", "test"]
    depends_on:
      - pom_tracker_db

